name: 'Chromatic Deployment'

on: push

jobs:
  test:
    name: Storybook Chromatic Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: yarn
      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
