name: Chromatic Deployment

on:
  push:
    branches:
      - develop
jobs:
  test:
    name: Storybook Chromatic Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: pnpm chromatic
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
